// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-avpqhm-z1rP2FsjfLfvTXYS-AZ-eNwM',
    appId: '1:1028509421824:web:892f779f33aa6a5a52e3e5',
    messagingSenderId: '1028509421824',
    projectId: 'portfolio-d2c93',
    authDomain: 'portfolio-d2c93.firebaseapp.com',
    storageBucket: 'portfolio-d2c93.appspot.com',
    measurementId: 'G-YR1RZB60PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16ifIba7dsCMWxrLMjObc-Nm1gIisgw4',
    appId: '1:1028509421824:android:f4c44de280cb839b52e3e5',
    messagingSenderId: '1028509421824',
    projectId: 'portfolio-d2c93',
    storageBucket: 'portfolio-d2c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ7KiXJkF5T2dUSU8uI5PUwiviPtR7BXk',
    appId: '1:1028509421824:ios:ac2ad5892774173052e3e5',
    messagingSenderId: '1028509421824',
    projectId: 'portfolio-d2c93',
    storageBucket: 'portfolio-d2c93.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ7KiXJkF5T2dUSU8uI5PUwiviPtR7BXk',
    appId: '1:1028509421824:ios:ac2ad5892774173052e3e5',
    messagingSenderId: '1028509421824',
    projectId: 'portfolio-d2c93',
    storageBucket: 'portfolio-d2c93.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-avpqhm-z1rP2FsjfLfvTXYS-AZ-eNwM',
    appId: '1:1028509421824:web:54ed13e9eef5791952e3e5',
    messagingSenderId: '1028509421824',
    projectId: 'portfolio-d2c93',
    authDomain: 'portfolio-d2c93.firebaseapp.com',
    storageBucket: 'portfolio-d2c93.appspot.com',
    measurementId: 'G-5C3R84E1LL',
  );
}
